<?php

const SUCURSAL = "SUCURSAL";
const SUC_ID = "SUC_ID";
const SUC_NOMBRE = "SUC_NOMBRE";
const SUC_UBICACION = "SUC_UBICACION";
const SUC_UBICACION_LINK = "SUC_UBICACION_LINK";
const SUC_IMAGEN = "SUC_IMAGEN";
const SUC_IMAGENES = "SUC_IMAGENES";
const SUC_ESTADO = "SUC_ESTADO";
