<?php

const SUCURSAL = "SUCURSAL";
const SUC_ID = "SUC_ID";
const SUC_NOMBRE = "SUC_NOMBRE";
const SUC_UBICACION = "SUC_UBICACION";
const SUC_ESTADO = "SUC_ESTADO";
const SUC_MODIFICACION = "SUC_MODIFICACION";
const SUC_ELIMINADA = "SUC_ELIMINADA";
